### ISSUE TITLE
Progressing the sleep field

### ISSUE THREAD

**Issue by jmkurka83** [wadpac/GGIR#106]
Hi Vincent,

I'm really looking forward to seeing where your GGIR and the LIDS analysis takes the concept of using actigraphy to detect sleep. Has there been any consideration into incorporating the established algorithms of Cole-Kripke (PMC: 1455130 [pmid]) or Sadeh (PMC: 7939118[pmid]) into GGIR? These algorithms, while much less advanced, remain as the accepted methods of scoring sleep from a behavioral standpoint. If these were incorporated into GGIR so an output would show Cole-Kripke, GGIR, and future scoring methods, it would enhance the ability to progress the field into accepting these more advanced methods.
Thoughts?
Thank you!

**Comment by vincentvanhees** [comment]
Hi Jonathan,

To my knowledge the Cole-Kripke or Sadeh are not published in a way that they can directly be applied to digital raw accelerometer data. They are partly based on analog signal processing steps, e.g. to calculate counts. Any software that claims to use the Cole-Kripke or Sadeh algorithm will need to have made some assumptions about how to imitate those original analog signal processing steps in digital signal processing. I once tried [to do that for a different traditional accelerometer brand](https://ieeexplore.ieee.org/document/5534986/?arnumber=5534986) and discovered that it is not a trivial step. I personally think that claims about Cole-Kripke or Sadeh algorithm replication should be supported by strong empirical evidence that new estimates are truly consistent with the original method, otherwise one is just fooling the software user by giving the misleading impression that a well establish algorithm is used.

Whether GGIR's approach to sleep detection has superior accuracy over Cole-Kripke or Sadeh remains to be proven, but that was never the reason why I attempted to design my own algorithm. The reason why I introduced a new approach is because the Cole-Kripke and Sadeh are not interpretable for research, while the algorithm I presented in [this](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0142533) paper is, because all variables and thresholds are expressed in a unit a researcher can interpret and the number of processing steps is very low.

Efforts at innovation are naturally discouraged by people's desire for methodological consistency, no matter how good the innovations are. The only way to break that pattern is by prioritising attempts for innovation over attempts for consistency. If someone would pay me for my time to try implement the Cole-Kripke or Sadeh algorithm I would do it.

**LIDS**
I have made a first implementation of the LIDS analysis in a [branch](https://github.com/wadpac/GGIR/tree/issue95_sleepstructure) of GGIR. As I only had a couple of weeks to do this, Eva Winnebeck who led on the original LIDS  method will now take over the development, such that it can eventially (upcoming 6 monts?) be added to GGIR. In the LIDS analysis I did not even try very hard to replicate the conventional actigraphy counts, but instead build a count metric that is not too difficult to explain, and produces an output that looks similar to what you would expect from the traditional method.

Vincent
