### ISSUE TITLE
Minor bug in g.conv.actlog when reading dates

### ISSUE THREAD

**Issue by jhmigueles** [wadpac/GGIR#1090]
When reading dates from an activity log in `g.conv.actlog`, the function `data.table::fread` loads the date columns with `class = "IDate" "Date" `. This triggers an error in check_log as it expects `class = character`.

Propose including this line in `g.conv.actlog` to make sure that all columns are introduced as character in `check_log`:
`actlog[, -1] = apply(actlog[, -1], 2, as.character)`

**Comment by vincentvanhees** [comment]
It would be good to understand what makes your dates different, because the function has worked for many years.  When I load a test csv file with a date column, fread just loads it as character.

The risk of first allowing `fread` to interpret the column as dates is that fread may change the format which then longer matches the format as provided by the user. So, if the problem is `fread` then I propose forcing `fread` to read the column as character during the reading process by adding argument `colClasses = "character"`.

**Comment by jhmigueles** [comment]
Thanks @vincentvanhees 

I found the source of the problem, `data.table::fread` would only read the date as class `IDate` if the date format is `%Y-%m-%d`. Here an example using the same log with different date formats, see the column classes for the date columns.

## %Y-%m-%d
```
Ymd = data.table::fread("logs/schoolTimes_GGIR.csv")
head(Ymd)
```
![image](https://github.com/wadpac/GGIR/assets/28734336/10df4ed6-302f-4fce-acb2-fa3b101ca1f4)


## %d/%m/%Y
```
dmY= data.table::fread("logs/schoolTimes_GGIR2.csv")
head(dmY)
```
![image](https://github.com/wadpac/GGIR/assets/28734336/be426f9e-c675-4257-87ce-7ca5e4334d9d)


Are you ok about adding the argument `colClasses = "character"` to make sure all columns are assigned the class character?

**Comment by vincentvanhees** [comment]
Yes, sounds good.
