### ISSUE TITLE
Error in `g.getmeta` object `'Gx'` not found

### ISSUE THREAD

**Issue by prinsherbert** [wadpac/GGIR#208]
For `g.shell.GGIR`, apparently `outputdir` shouldn't be a child directory of `datadir` .

A check whether outputdir starts with datadir, which then raises an error, would be nice.

For future reference to others walking into this isue, this was my debugging procedure:

If so, running part 1 on Acrigraph CSV-files, I run into this error message.

    Error in g.getmeta(datafile, do.bfen = do.bfen, do.enmo = do.enmo, do.lfenmo = do.lfenmo,  : 
      object 'Gx' not found

Unfortunately, my Rstudio setup does not show line numbers in tracebacks, so I had to *unfold* the functions `g.shell.GGIR`, `g.part1` and `g.getmeta` in one script to figure out where this comes from. Any suggestions for more effective debugging are very welcome :)

This seems to be the issue, and in fact this is the first read use of `Gx` in `g.getmeta`, before any assignment has been done.

https://github.com/wadpac/GGIR/blob/master/R/g.getmeta.R#L302

The variable is however also created in `g.calibrate`, but not returned or exported in any way, as far as I can tell:

https://github.com/wadpac/GGIR/blob/master/R/g.calibrate.R#L105

Moreover, it seems explicitly deleted:

https://github.com/wadpac/GGIR/blob/master/R/g.calibrate.R#L187

And also explicitly assigned a later point in `g.getmeta`:

https://github.com/wadpac/GGIR/blob/master/R/g.getmeta.R#L325

**Comment by vincentvanhees** [comment]
Thanks, I have now added a check for _outputdir_ and _datadir_ in function _g.part1_, from where _g.gemeta_ and _g.calibrate_ are called. The code will now throw an error warning if _outputdir_ = _datadir_ or if it is a subdirectory of _datadir_.

**Gx**
I use 'Gx' as name of the raw acceleration signal for the x-axis. It is only used inside the function. The idea of GGIR is that the user is interested in the aggregated data. I used _g.getmeta_ as a template when I wrote _g.calibrate_ hence the overlap in names. A more accurate name for function _g.getmeta_ would have been loadDataAndExtractSignalFeatures. I am aware that GGIR has quite a number of functions and object names that could be more intuitive. I am hesitant updating the names, because it could break consistency with older versions. So, my plan is to collect all ideas for terminology improvements and implement them in the transition to GGIR version 2.0.

**Debugging**
What works for me is a combination of:
- After error occurs, click 'Run with debug' button that will appear inside the console.
- If you know where the error occurs use RStudio's debugging mode (click left of a line resulting in red dot, and then source the script).
- If the error messages shows a specific bit of code, then search the github repository for that specific phrase.

**General architecture of GGIR**
In the upcoming months a paper will be published online with a high level overview of how GGIR is structured and what it can do. I will add a reference to the paper once it is online. In addition, I may at some point try to add a call graph to the repository as extra guidance for people trying to fix bugs.
