### ISSUE TITLE
Weird hard coded window size for rolling median when calculating angle metrics and inefficient rolling median

### ISSUE THREAD

**Issue by prinsherbert** [wadpac/GGIR#328]
# Window size 
[The window size used for the rolling median here](https://github.com/wadpac/GGIR/blob/master/R/g.metric.R#L66) is hard coded to 5 seconds, which is also the default small window size (often referenced by as `ws3` or `windows(1)`). Would it make sense to use the small window size instead? 

# Mean of medians
Using these windows, [the mean](https://github.com/wadpac/GGIR/blob/master/R/g.applymetrics.R#L31) of [several medians from rolling windows](https://github.com/wadpac/GGIR/blob/master/R/g.metric.R#L68) is computer for every 5 second window.

I am suspecting this rolling median filter is slowing down the computation, since it might be O(signal_length * window_length). Have you considered using the mean of the median 50% of each 5 second window instead? This would be O(signal_length * log(window_length)).

I've implemented an [alternative to part 1 GGIR](https://github.com/prinsherbert/girrgorr/blob/master/girrgorr/metrics.py#L30) which is about 10 times faster in processing a CSV to 5 second aggregations. Because so far the speed is limited by IO the most, I expect it to stay similarly fast when other features of part1 that I've skipped would be added, like the calibration and the other metrics. So it might be interesting to track down where the processing time of step 1 goes to.

**Comment by vincentvanhees** [comment]
#### Window size
Window size is hard coded because it acts as a 0.2 Hertz frequency filter. If we would let it scale with for example a 1 second small window size it would become a 1 Hertz filter, which is undesirable. So, sticking with 5 seemed safest option.

#### Mean of median
You are right, this does not look efficient. Probably I was too busy with the interpretation of the calculation and did not think enough about computational speed. I suspect that 5 second by 5 second median calculations could also work, but it would be important to check that the final estimates are very similar. Another route could be to look out for a rolling median filter that skips samples, to arrive at a lower resolution rolling median.

#### General speed of GGIR part 1
Great to hear about your Python development. GGIR relies on the data.table package for reading in csv files, which within R is considered a fast way to read csv data. The calibration procedure reads in the raw data in addition to reading the raw data as part of the feature calculation process. The calibration procedure does not necessarily need the whole file, but by default it will read at least 3 days of data. This will slow down the process by a factor of 1.3 up to 2, in case the calibraiton algorithm wants to see all the raw data. This double loading seems unavoidable because without calibration coefficients derived from all the raw data it is impossible to start calculating signal features. The only solution would be to load in all the data in memory and do all the procedures on the raw data in memory, but the machines I worked with when I started with GGIR could not handle that. Also, I suspect that it is still convenient for GGIR users to know that GGIR can do its work even on simple low memory laptops.

However, I made some effort to address this for researchers who want to repeatedly process the same files, I have designed GGIR to recognize when the calibration procedure has been done in a previous run on the same files. It will then obtain the previously generated calibration correction coefficients (stored in QC output folder) and skip the procedure.

On a different note - you may want to check out the monthly webinar series I am coordinating [here](https://github.com/wadpac/oss-dev-webinar-series-pb-field/blob/master/README.md). Maybe of interest to you.
