### ISSUE TITLE
g.getmeta(...) seems to skip 15 minutes of the start

### ISSUE THREAD

**Issue by prinsherbert** [wadpac/GGIR#335]
I'm not sure if this is intended behavior, but it seems `g.getmeta(...)` output in metashort skips the first 15 minutes of data.

![image](https://user-images.githubusercontent.com/7011110/90249388-a8390500-de3a-11ea-8dc9-7f6cd7b85fd6.png)

*EDIT* at the end `g.getmeta(...)` are also seems to drop some samples at the end.

![image](https://user-images.githubusercontent.com/7011110/90249603-0b2a9c00-de3b-11ea-9652-33a7769df97a.png)

**Comment by vincentvanhees** [comment]
This is intentional to make aggregated data comparable in time between different recordings.
GGIR looks for the first integer of long windowsizes (second object windowsizes) in the hour and starts data aggregation at that time point.

For example, start recording A is at 10:01, and start recoridng B is at 10:09,
If long windowsize is 15 minutes the output for both will start at 10:15.
If long windowsize is 10 minutes the output for both will start at 10:10.
If long windowsize is 5 minutes the output for A will start at 10:05, while output for B will start at 10:10.

In this way it is also much easier to describe behaviour per day, because none of the epochs overlaps with midnight. This would be the case if you would simply start aggregating epochs relative to the start of the recording.
