### ISSUE TITLE
ActiLife counts in GGIR

### ISSUE THREAD

**Issue by jhmigueles** [wadpac/GGIR#591]
ActiLife counts have become available in R. It would be great to investigate whether they can be calculated within the GGIR pipeline as a new acceleration metric to be used in GGIR.

**Comment by vincentvanhees** [comment]
Last year's implementation of BrondCounts in GGIR (no longer as external function) may be a good example for how to implement this.

BrondCounts are also an attempt to imitate ActiLife counts, so it would be good to make sure the GGIR documentation is clear about the differences and origin of each approach. For BrondCounts I have intentionally chosen not to refer to them as ActiGraph Counts because it will cause confusion given the various attempts to imitate ActiGraph counts in the past. We should also not exclude the possibility that the ActiGraph company will at some point release the algorithms that correspond to different older or newer versions of ActiLife or an algortihm to imitate the Counts produced by the earlier ActiGraph hardward (GT1M and earlier).

Some ideas:
1. Call the metric ActiLifeCounts but add a separate input argument to specify which algorithm should be used, e.g. BrondCounts2019 or Neishabouri2022, where Neishabouri2022 would be the default. In that way we allow for some future flexibility to integrate alternative count algorithms.
2. Call it "Counts" and add separate input arguments to specify the algorithm, because in that way we can include a much broader range of count algorithms, including the algorithms to imitate counts from other sensor brands. The disadvantage is that it will be harder to use multiple count-definetions in parallel.
3. Call it NeishabouriCounts and clarify in the documentation the link with ActiLife and the paper. This would be most in line with the current naming of BrondCounts in GGIR.
