### ISSUE TITLE
results of part 4 and part 5 are different

### ISSUE THREAD

**Issue by yummyyimao** [wadpac/GGIR#683]
Dear professor van Hee,

Sorry to trouble you again. I am learning to use the GGIR for analyzing sleep parameters of ukb dataset. I encountered with some problems: Firstly, I found part4 and part5 both have the results of sleep parameters and I wonder to know which part would be the final results (as part4 has more days for per person). Secondly, as ukb has no sleep logs, I prefer to adapt the guider parameters of sleep (method HDCZA). In this way, I wonder to know if I have to re-calculate the WASO, as well as sleep efficiency.

Thank you for your kindly help,
Best wishes to you
Yimeng

**Comment by vincentvanhees** [comment]
Hi Yimeng, GGIR part 4 attempts to provide a sleep analysis for as many nights in the data as possible. Further, part 4 output variable names are intended to align with sleep literature.

GGIR part 5 does not focus on sleep and only uses the sleep estimates from part 4 in it's attempt to characterise full day time-use. If a day does not have sufficient daytime valid data or lacks clear estimates of sleep in the night before or after the day then the day is skipped even if sleep estimates may be available form one of the adjacent nights in part 4. So, if your focus is on sleep analyses: Use GGIR part 4 output.

If you run GGIR with HASPT.algo = "HDCZA" without specifying loglocation then WASO should automatically be calculated.
Sleep efficiency is not calculated in part 4 because ideally we need to know the time of intention to fall asleep. This depends on access to a sleeplog that asks the participant about this.
