### ISSUE TITLE
Implement DFA analysis

### ISSUE THREAD

**Issue by vincentvanhees** [wadpac/GGIR#839]
Implement DFA analysis based on code provided by Ian.

To do:
- [x] Select variables to output (we only need ABI and SSP)
- [x] Decide which functions will be internal/external
- [x] Prepare functions with Rd file documentation and unit-test
- [x] Store variables in output
- [x] Merge with cosinor work which relates to same part of function `g.part5`

**Comment by vincentvanhees** [comment]
Hi @iandanilevicz and @victormesquita40

This is a heads-up that I am now implementing the DFA, SSP and ABI functions you wrote last year:
- Even though you are listed in the code as author, I will also add you as co-author to the git commit such that it is clear from the git history that you did the work. You will probably receive a notification about this.
- I am preparing all this in a git branch which I will turn into a pull request later today. I will not merge the pull request without Ian's approval (we will meet on Friday).
- I have made minor changes to the exception handling, which I will explain in the pull request. The algorithm itself is the same as how you provided it to me.

**Comment by victormesquita40** [comment]
Hi people,

I made some promises to Ian about the code that I would review, but unfortunately, due to the lack of time, I couldn't.

Ian has some projects with Paulo Canas, who spoke highly of Ian to me, so he has my authorization to update the DFA package and its functions.

Please keep me updated on the progress of the versions.

Regards,

Victor

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vincentvanhees** [comment]
Close this issue, because this is covered by https://github.com/wadpac/GGIR/issues/955 and will be merged paper has been written.
